crate/crate-clients-tools

docs/index.rst
Hi there,
I feel the red crosses on [1] are a bit too visually disturbing and might signal danger. At least, it does to my eyes. Instead, it should just signal that CrateDB does not offer official support. I believe having just checkmarks for all adapters with official support is more than sufficient.
With kind regards,
Andreas.
[1] https://crate.io/docs/crate/clients-tools/en/latest/#clients
=> Remove visual cross designation on all non-official client adapters

.github/workflows/docs.yml, .gitignore, .readthedocs.yml, BACKLOG.md, DEVELOP.rst, LICENSE, MAINTAINERS.rst, README.rst, docs/analyze.md, docs/build.json, docs/cli.md, docs/connect/index.md, docs/connect/java.rst, docs/connect/javascript.rst, docs/connect/php.rst, docs/connect/python.rst, docs/connect/ruby.rst, docs/etl.md, docs/ide.md, docs/index.md, docs/legacy.rst, docs/visualize.md
Together with other patches, this aims to rework and modernize the appearance of the `crate-clients-tools` repository and its contents, which is being published to https://crate.io/docs/clients/, and did not receive much love for a long time.
https://crate-clients-tools--33.org.readthedocs.build/en/33/
- https://github.com/crate/cloud-docs/pull/9
- https://github.com/crate/crate/pull/14521
/cc @karynzv, @marijaselakovic, @hlcianfagna, @hammerhead, @msbt, @ckurze
=> NG: Thoroughly modernize content and appearance

docs/analyze.md, docs/etl.md
Last week, @hlcianfagna and @hammerhead published the article [Using dbt with CrateDB](https://community.crate.io/t/using-dbt-with-cratedb/1566). Thanks. This patch also adds a corresponding item to the "etl" section, and also links to that article.
https://crate-clients-tools--41.org.readthedocs.build/en/41/etl.html#dbt
=> Add item about dbt to "etl" section

docs/analyze.md, docs/etl.md
@marijaselakovic published the article [Setting up data pipelines with CrateDB and Kestra](https://community.crate.io/t/setting-up-data-pipelines-with-cratedb-and-kestra-io/1400) the other day already. Thanks. This patch also adds a corresponding item to the "etl" section, and also links to that article.
https://crate-clients-tools--42.org.readthedocs.build/en/42/etl.html#kestra
=> Add item about Kestra to "etl" section

BACKLOG.md, docs/analyze.md, docs/conf.py, docs/etl.md, docs/visualize.md
As suggested by @proddata, this adds managed service offerings to corresponding integration items. It does not obstruct the visual appearance too much, by using [sphinx{design} Dropdowns](https://sphinx-design.readthedocs.io/en/latest/dropdowns.html) for the new content.
Let me know if you think I missed some important items to expand, or if you can think of any details which should be added to the new collapsed dropdown sections in one way or another.
- https://crate-clients-tools--43.org.readthedocs.build/en/43/etl.html
- https://crate-clients-tools--43.org.readthedocs.build/en/43/visualize.html
=> Add managed service offerings to integration items

docs/conf.py, docs/connect/index.md, docs/index.md, docs/integrate/analyze.md
- Naming things: Use "Driver" instead of "Library"
- Naming things: Add Node.js
- Naming things: Use "CrateDB xxx driver" to designate its origin
- Add Ruby driver and ActiveRecord adapter
- Fix build: ML sandbox repository got depublished
=> This and that: Naming things, Ruby driver/adapter

docs/connect/cli.md, docs/connect/index.md
This patch slightly improves the wording on the https://crate.io/docs/crate/clients-tools/en/latest/connect/cli.html page. Thanks, @hlcianfagna.
=> [connect/cli]: Improve wording and variable/template explanations

docs/conf.py, docs/index.md, docs/integrate/bi.md, docs/integrate/ml.md, docs/integrate/visualize.md
Just a little refactoring to set the stage for a few content additions. The content wasn't changed much, but merely moved around.
/cc @surister
=> Integrate: Split "Analyze" section into BI vs. ML

docs/connect/index.md, docs/integrate/etl.md
At GH-56, we reported that the [node-crate](https://www.npmjs.com/package/node-crate) library got lost on the recent refactoring. This patch brings it back to the contemporary section about [Database Drivers](https://cratedb.com/docs/crate/clients-tools/en/latest/connect/#client-libraries).
=> Connect: Re-add `node-crate` library. It is maintained.

docs/connect/df.md
Accompanying other patches, this one adds a section about the Polars Dataframe library to the documentation.
- https://pola.rs/
- https://docs.pola.rs/
https://crate-clients-tools--65.org.readthedocs.build/en/65/connect/df.html#polars
- https://github.com/crate/cratedb-examples/issues/228
- https://github.com/crate/cratedb-examples/pull/229
/cc @hlcianfagna
=> Dataframes: Add section about the Polars Dataframe library

docs/integrate/visualize.md
This patch extends the list of available resources about Apache Superset.
/cc @hlcianfagna
=> Visualize: Add more links to resources about Apache Superset

docs/connect/df.md
Maintenance patch to compensate a location update.
- https://github.com/crate/cratedb-examples/pull/265
=> Dataframes: Fix links to code examples about pandas and Dask

docs/connect/index.md, docs/integrate/etl.md, docs/integrate/visualize.md
The directory layout at `cratedb-examples` has been improved. This patch compensates for that.
- https://github.com/crate/cratedb-examples/pull/271
- https://github.com/crate/cratedb-examples/pull/278
=> Fix broken links after adjusting folder layout at `cratedb-examples`

docs/index.md, docs/integrate/etl.md, docs/integrate/metrics.md
- Add dedicated page about metrics/monitoring
- Improve section about Telegraf
- Add section about Prometheus and CrateDB Prometheus Adapter
https://crate-clients-tools--70.org.readthedocs.build/en/70/integrate/metrics.html
=> Metrics: Prometheus and Telegraf

docs/connect/index.md, docs/integrate/etl.md
This patch adds an item about the PostgreSQL ODBC driver to the list of supported drivers, and a section about SQL Server Integration Services to the ETL page. Thanks for verifying, @hlcianfagna, and for providing a hands-on example.
- https://crate-clients-tools--62.org.readthedocs.build/en/62/connect/index.html#overview
- https://crate-clients-tools--62.org.readthedocs.build/en/62/integrate/etl.html#sql-server-integration-services
- https://github.com/crate/cratedb-examples/pull/262
For satisfying CI, the PR https://github.com/crate/cratedb-examples/pull/262 needs to be merged beforehand.
=> Driver+ETL: ODBC and SSIS

docs/connect/index.md
Similar to how that other patch for cratedb-examples does it, this one adds a few badges to inform about the latest release version and its build status on CI, for each driver.
- https://github.com/crate/cratedb-examples/pull/277
https://crate-clients-tools--72.org.readthedocs.build/en/72/connect/index.html#overview
=> Drivers: Add badges about latest version and build/ci status

docs/index.md
On the recent refactoring, we missed to add a corresponding item "System Metrics" to the wall of integration families.
- GH-70
While being at it, that patch also adjusts the general layout a bit.
https://crate-clients-tools--73.org.readthedocs.build/en/73/#integrations
=> Home: Improve layout of integrations wall. Add "System Metrics" card.

docs/connect/index.md, docs/index.md, docs/status.md
The build status of relevant drivers, applications, and integrations for CrateDB, on one page. Will make parts of https://github.com/crate/cratedb-examples/pull/277 obsolete again.
Maybe you can spot some missing item you would like to see enumerated here?
https://crate-clients-tools--75.org.readthedocs.build/en/75/status.html
/cc @karynzv, @marijaselakovic, @hlcianfagna, @wierdvanderhaar
=> Status: Add a dedicated "Build Status" page

docs/_static/style.css, docs/conf.py, docs/connect/index.md, docs/status.md
The previous layout was no longer able to sustain content pressure without becoming even more confusing about the discrimination between PostgreSQL-based drivers, and HTTP-based ones.
The new approach is to have dedicated sections for each of them. It aims to provide a better guidance than a single list of mixed items.
before: https://cratedb.com/docs/crate/clients-tools/en/latest/connect/
after: https://crate-clients-tools--77.org.readthedocs.build/en/77/connect/
/cc @karynzv, @marijaselakovic, @proddata, @matriv, @seut
=> Connect: Adjust layout of index page about client drivers

docs/integrate/etl.md
This patch adds a few missing links to the ETL/Astronomer section.
https://crate-clients-tools--79.org.readthedocs.build/en/79/integrate/etl.html#apache-airflow-astronomer
=> ETL: Add references to tutorials how to connect Astro and CrateDB Cloud

docs/index.md, docs/integrate/testing.md
This patch adds a dedicated page which is indexing a few resources about software integration testing with Java and Python.
- native: Python unittest, using cr8
- native: pytest-crate, using cr8
- testcontainers: Testcontainers for Java
- testcontainers: Testcontainers for Python (pytest and unittest)
- https://github.com/crate/cratedb-examples/pull/280
- https://crate-clients-tools--80.org.readthedocs.build/en/80/#id1
- https://crate-clients-tools--80.org.readthedocs.build/en/80/integrate/testing.html
/cc @karynzv, @hlcianfagna, @marijaselakovic, @seut
=> Testing: Add page about software testing with CrateDB (Java and Python)

BACKLOG.md, DEVELOP.rst, LICENSE, README.rst, docs/Makefile, docs/connect/cli.md, docs/connect/ide.md, docs/connect/index.md, docs/index.md, docs/integrate/bi.md, docs/integrate/etl.md, docs/integrate/metrics.md, docs/integrate/visualize.md, docs/legacy.rst
Rename all references to crate.io to cratedb.com, where applicable. Also, use `https://` everywhere where `http://` has been used before.
=> Chore: Use cratedb.com, and https:// everywhere

docs/build.json, docs/conf.py, docs/connect/ide.md
DataGrip needed to be retracted from GH-33, because it does not work [well] with CrateDB.
https://crate-clients-tools--35.org.readthedocs.build/en/35/connect/ide.html
- https://github.com/crate/crate/issues/12101
- https://github.com/crate/crate/discussions/10841
=> IDE: Add DataGrip

docs/integrate/bi.md
> Rill takes a modern approach to Business Intelligence (BI), which is starting to leverage software engineering principles by implementing the concept of BI as code.
@proddata verified it works well together with CrateDB. Thanks!
-- [Introducing Rill and BI as Code with CrateDB Cloud](https://community.cratedb.com/t/introducing-rill-and-bi-as-code-with-cratedb-cloud/1718)
https://crate-clients-tools--71.org.readthedocs.build/en/71/integrate/bi.html#rill
=> BI: Add item about Rill

docs/conf.py, docs/connect/df.md, docs/connect/orm.md, docs/index.md, docs/integrate/bi.md, docs/integrate/etl.md, docs/integrate/metrics.md, docs/integrate/ml.md, docs/integrate/visualize.md
After all the tutorials have been refactored into the CrateDB Guide with GH-82 recently, the enumeration of catalog items here became a bit of a lost place. Thanks for reporting, @geragray.
The patch concludes the renovation on this end, by effectively repurposing the documentation section into a (preliminary) ecosystem software catalog/gallery, in the spirit how [others](https://cloud.mongodb.com/ecosystem/) [are](https://catalog.redhat.com/) [running](https://hub.docker.com/) [them](https://hub.meltano.com/).
To remedy a guidance flaw, the patch also adds concise navigation elements to the top of each page within its "Integrations" section, by adding gravity towards the corresponding tutorial items, now located within _The CrateDB Guide_. 
Two samples of that have been outlined below, …
=> Renovate: Repurpose into "CrateDB Ecosystem Catalog"

docs/connect/index.md, docs/connect/python.rst
- We found [aiopg](https://github.com/aio-libs/aiopg) has not been enumerated in the list of canonical supported client drivers for Python.
- Along the lines, the patch improves a a few spots in the same area while on it already.
=> Client Drivers: Add `aiopg` to list of supported Python drivers

docs/legacy.rst
Just a link update, currently the initial URL redirects from
https://cratedb.com/docs/reference/jdbc
to
https://cratedb.com/docs/reference/jdbc/
to
https://cratedb.com/docs/clients/jdbc/en/latest/
to
https://cratedb.com/docs/jdbc/en/latest/
This points to the last URL in the chain
=> Update legacy.rst to avoid redirect chain

docs/integrate/etl.md
@wierdvanderhaar and @hlcianfagna recently verified connectivity to Apache Hop, aka. the »Hop Orchestration Platform«, thanks! This patch intends to add a corresponding item to the documentation.
https://crate-clients-tools--64.org.readthedocs.build/en/64/integrate/etl.html#apache-hop
- https://hop.apache.org/
- https://github.com/apache/hop/
=> ETL: Add section about Apache Hop

docs/conf.py, docs/integrate/etl.md
Now after adding the item about [Apache Hop](https://github.com/crate/crate-clients-tools/pull/64), let's also add an item about Apache NiFi.
https://crate-clients-tools--125.org.readthedocs.build/en/125/integrate/etl.html#apache-nifi
=> ETL: Add Apache NiFi

docs/connect/index.md, docs/connect/python.rst, docs/requirements.txt
The [CrateDB SQLAlchemy dialect](https://github.com/crate-workbench/sqlalchemy-cratedb) needs more love, so it was separated from the [DBAPI HTTP driver](https://github.com/crate/crate-python). This patch intends to accompany the migration.
=> Python: Add new project `sqlalchemy-cratedb`

docs/index.md, docs/integrate/framework.md
Add basic information about Gradio and Streamlit, in order to quickly establish relevant keywords.
https://crate-clients-tools--132.org.readthedocs.build/en/132/integrate/framework.html
- https://github.com/crate/cratedb-examples/pull/506
- https://github.com/crate/cratedb-examples/pull/507
/cc @simonprickett, @proddata
=> Framework: Add items about programming frameworks Gradio and Streamlit

docs/status.md
- [cratedb-examples](https://github.com/crate/cratedb-examples) gained a few more integration testing slots: Gradio, Streamlit, LlamaIndex.
- [sqlalchemy-cratedb](https://github.com/crate/sqlalchemy-cratedb) and [cratedb-sqlparse](https://github.com/crate/cratedb-sqlparse) had been forgotten.
- [academy-fundamentals-course](https://github.com/crate/academy-fundamentals-course) as well as [micropython-cratedb](https://github.com/crate/micropython-cratedb) gained test harnesses.
Thanks for your contributions.
https://crate-clients-tools--146.org.readthedocs.build/en/146/status.html
/cc @karynzv, @hlcianfagna, @wierdvanderhaar, @surister, @zolbatar, @kneth
=> Build Status: Add badges for new projects and unlocked integrations

docs/status.md
Otherwise, the badge will always display the _latest_ test outcome, which includes outcomes from arbitrary PR job runs. This is not intended. Instead, the badges aim to display the status of the head branch.
https://crate-clients-tools--147.org.readthedocs.build/en/147/status.html
/cc @kneth
=> Build Status: Use explicit branch names

docs/connect/index.md
It adds the new MicroPython client to the list of clients that use the HTTP API.
https://crate-clients-tools--145.org.readthedocs.build/en/145/connect/index.html#http
=> Added MicroPython client to list of HTTP protocol clients.

docs/status.md
Found that [pytest-cratedb](https://github.com/crate/pytest-cratedb) was still missing. It has been refreshed only recently after forking it from its predecessor.
https://crate-clients-tools--149.org.readthedocs.build/en/149/status.html
=> Build Status: Add `pytest-cratedb` project

docs/connect/index.md
A few fixes/improvements to different connection strings we are presenting on the documentation. For example:
- Add missing `ssl=true` argument on SQLAlchemy connection string.
- Remove `/<dbname>` argument from SQLAlchemy connection string, because it would cause errors.
https://crate-clients-tools--151.org.readthedocs.build/en/151/connect/
/cc @surister, @simonprickett
=> Connect: Fix and improve connection strings

docs/integrate/etl.md, docs/integrate/ml.md, docs/integrate/visualize.md
Refactor catalog elements to in-context pages in CrateDB Guide, to make progress towards "monorepo"-style docs management as good as possible.
- https://github.com/crate/cratedb-guide/pull/145
=> Integration catalog widgets: Refactor into CrateDB Guide, part 1

docs/status.md
Adding the CI outcome of `langchain-cratedb` here is the least we can do
to keep it on the radar for monitoring the outcome of the nightly
integration job on a daily basis.
-- https://cratedb.com/docs/crate/clients-tools/en/latest/status.html
-- https://github.com/crate/langchain-cratedb/actions/workflows/ci.yml
https://crate-clients-tools--220.org.readthedocs.build/en/220/status.html
=> Build Status: Add `langchain-cratedb`

docs/status.md
The new Tableau connector significantly gained maturity, now at >95% test cases succeeding, and dearly needs a representation on the [Build Status](https://cratedb.com/docs/crate/clients-tools/en/latest/status.html) page.
https://crate-clients-tools--229.org.readthedocs.build/en/229/status.html#applications-connectors-sdks
- https://github.com/crate/cratedb-tableau-connector/pull/33
=> Build Status: Add badge/shield about Tableau

docs/status.md
The new Estuary connector was quickly merged upstream, and dearly needs a representation on the [Build Status](https://cratedb.com/docs/crate/clients-tools/en/latest/status.html) page.
https://crate-clients-tools--230.org.readthedocs.build/en/230/status.html#applications-connectors-sdks
- https://github.com/estuary/connectors/pull/2452
- https://github.com/estuary/connectors/pull/2477
=> Build Status: Add badge/shield about Estuary

docs/status.md
The new Fivetran connector is in its infancy, but clocking in with ~75% feature coverage, it may also have a representation on the [Build Status](https://cratedb.com/docs/crate/clients-tools/en/latest/status.html) page right away.
https://crate-clients-tools--231.org.readthedocs.build/en/231/status.html#applications-connectors-sdks
- https://github.com/crate-workbench/cratedb-fivetran-destination/pull/4
=> Build Status: Add badge/shield about Fivetran

docs/status.md
- Completes https://github.com/crate/cratedb-examples/pull/869.
=> Build Status: Add badge about "Go pgx"

.github/workflows/docs.yml
Update CI recipe to align with others - primarily reducing build time.
=> CI: Only build on Ubuntu.

docs/status.md
Two new public repositories surfaced recently.
- https://github.com/crate/about
- https://github.com/crate/cratedb-mcp
=> Build Status: Add badges about "About CrateDB" and "CrateDB MCP"
