crate/crate-clients-tools

docs/index.rst

https://github.com/crate/crate-clients-tools/issues/1
Part of Q3 2020 effort to update the docs
Summary
- changed 'driver' to 'name' since I don't think 'driver' is synonymous with 'client'
- restructured flow
- sorted, fixed, and updated links
- added more tools
- corrected some things in the table
- added an example

Update Clients and Tools page

---

docs/index.rst

Hi there,
I discovered that two PHP client drivers / integration adapters were missing on the list. This patch improves the situation.
With kind regards,
Andreas.

Add CrateDB DBAL driver and CrateDB Laravel integration adapters

---

docs/build.json
docs/index.rst

As suggested by @proddata at #22, this reorders the list of client drivers for the sake of improved discoverability. It also swaps the column order to make the language come first.
At the same time, it bumps to the most recent version of the docs build infrastructure.

Reorder list of client drivers / adapters

---

.mergify.yml
docs/Makefile
docs/build.json
docs/index.rst

Will bring Sphinx 5 to the documentation sandbox.

Update to crate-docs 2.1.0

---

docs/index.rst

- It seems that there are currently [no issues](https://github.com/crate/crate/issues?q=is%3Aopen+is%3Aissue+label%3A%22driver%3A+PostgreSQL+JDBC%22) for JDBC. Does it make sense to remove this mention?

Remove known issues mention

---

docs/visualize.md

Chore: Fix broken links

---

docs/visualize.md

@matkuliak just published the article [Data Analysis with Cluvio and CrateDB](https://community.crate.io/t/data-analysis-with-cluvio-and-cratedb/1571). Thanks. This patch also adds a corresponding item to the "visualization" section, and also links to that article.
https://crate-clients-tools--40.org.readthedocs.build/en/40/visualize.html#cluvio

Add item about Cluvio to "visualization" section

---

docs/integrate/visualize.md

Bringing in a few more cross-links to related resources.

Visualize: Add link to webinar about Apache Superset / Preset

---

docs/connect/df.md
docs/connect/orm.md
docs/connect/python.rst
docs/index.md
docs/integrate/etl.md
docs/integrate/ml.md
docs/integrate/visualize.md

- Integrate: Add dedicated pages about DataFrames (pandas, Dask) and ORMs (SQLAlchemy)
- Integrate/Visualize: Add items about Dash, hvPlot, Datashader, Plotly
- Integrate/ML: Add items about LangChain, MLflow, and PyCaret
- Integrate/ETL: Add item about Singer/Meltano
- Connect/Python: Add item about Psycopg 3
- https://crate-clients-tools--54.org.readthedocs.build/en/54/
/cc @andnig, @surister, @matkuliak

Integrate: Add items about Psycopg 3, pandas, Dask, SQLAlchemy, Dash, hvPlot, Datashader, Plotly, Singer/Meltano, LangChain, MLflow, PyCaret

---

docs/index.md

»CrateDB Clients and Tools« just doesn't cut it.
»CrateDB Drivers and Integrations« is better I guess?

Home: Update main title to better reflect what's inside

---

docs/integrate/bi.md

Add link targets for cratedb-guide.
- https://github.com/crate/cratedb-guide/pull/54

Chore: Add link anchors to PowerBI and Tableau sections

---

docs/status.md

Build Status: Add build status badge for "Time Series"

---

docs/integrate/framework.md
docs/integrate/visualize.md

After adding a new section "Programming Frameworks" by GH-132, this patch refactors a few other items into that new section, more specifically Dash/Plotly, and hvPlot/Datashader.
https://crate-clients-tools--133.org.readthedocs.build/en/133/integrate/framework.html
- GH-132
/cc @simonprickett, @proddata

Framework: Refactor a few items from "Visualization"

---

docs/conf.py
docs/integrate/metrics.md

Chore: Fix broken reference to CrateDB Guide

---

docs/connect/index.md
docs/integrate/bi.md
docs/integrate/etl.md
docs/integrate/ml.md
docs/status.md

Fix too narrow column widths in two tables.
https://crate-clients-tools--142.org.readthedocs.build/en/142/connect/#client-libraries
- GH-141

Fix column widths on connect/index page

---

docs/status.md

- [Add framework-dbt slot in cratedb-examples](https://github.com/crate/crate-clients-tools/commit/c00168a986d5c61e3b9252d6c8b059598536d8e1)
- [Add item crate-java-testing](https://github.com/crate/crate-clients-tools/commit/63e5f1f3ed4cb7d688ca5c5356eaa678116c4fd4)
- [Fix crate-python driver slot](https://github.com/crate/crate-clients-tools/commit/bc52f257e56cb556bfc150656015603b08b4df60)
- [Regroup drivers vs. SDKs and others](https://github.com/crate/crate-clients-tools/commit/906999a49783e2fc79df972e37f2231a907fbb9f)
https://crate-clients-tools--150.org.readthedocs.build/en/150/status.html

Build Status page: This and that

---

docs/status.md

- [Build Status: Fix badge about Apache Flink, now slotted into "Framework"](https://github.com/crate/crate-clients-tools/commit/293558e6f98c5c83c710c247a41756f08be089b4)
- [Build Status: Add badges about CrateDB Toolkit and Metabase](https://github.com/crate/crate-clients-tools/commit/80b32b0e4c6d8eb9cf169c38454373ebb1572cb0)

Fix build status page

---

docs/status.md

Reference integration tests with Model Context Protocol (MCP).
- https://github.com/crate/cratedb-examples/pull/853

Build Status: Add badge about tests with Model Context Protocol (MCP)

---

docs/status.md

Reference integration tests with C# / EF Core. Thanks, @hlcianfagna.
- https://github.com/crate/cratedb-examples/pull/854

Build Status: Add badge about tests with C# / EF Core

---

docs/status.md

Just a few maintenance updates to the badges on the [Build Status](https://cratedb.com/docs/crate/clients-tools/en/latest/status.html) page.

Build status: This and that

---

docs/status.md

Reference integration tests with Elixir ([Postgrex](https://hexdocs.pm/postgrex/)), R ([RPostgreSQL](https://cran.r-project.org/web/packages/RPostgreSQL/)), and Rust ([postgres](https://crates.io/crates/postgres)).
- https://github.com/crate/cratedb-examples/pull/857
- https://github.com/crate/cratedb-examples/pull/856
- https://github.com/crate/cratedb-examples/pull/855

Build Status: Add badges about Elixir, R, and Rust

---

docs/integrate/bi.md

Chore: Fix broken links to images on rilldata.com

---

docs/requirements.txt

Probing some fixes and improvements.
https://crate-clients-tools--246.org.readthedocs.build/
- https://github.com/crate/crate-docs-theme/pull/594
- https://github.com/crate/crate-docs-theme/pull/596
- https://github.com/crate/cratedb-guide/pull/194

Dependencies: Update to crate-docs-theme 0.38.4

---

docs/status.md

Add a badge based on corresponding adjustments to the downstream project.
- https://github.com/surister/cratedb-django/pull/4

Build Status: Add badge about "Django"
